version: "3.9"
services:
    backend:
        image: lecreditapicole
        container_name: lecreditapicole
        build:
            context: ./lecreditapicole
        ports:
            - "9000:80"
    frontend:
        image: lecreditapicole-ui
        container_name: lecreditapicole-ui
        build:
            context: ./lecreditapicole-ui
        ports:
            - "80:80"
        depends_on:
            - backend
        links: 
            - backend